mongo:
  image: mongo
  volumes:
    - /var/opt/fpauth_db:/data/db
node:
  build: .
  links:
    - mongo:mongo
  environment:
    - FPAUTH_LOG_LEVEL=info
    - FPAUTH_DISCORD_TOKEN=
    - FPAUTH_GUILD=
    - FPAUTH_WELCOME_CHANNEL=
    - FPAUTH_MOD_CHANNEL=
    - FPAUTH_MEMBER_ROLE=
    - FPAUTH_GOLDMEMBER_ROLE=
    - FPAUTH_MODERATOR_ROLE=
    - FPAUTH_UPDATE_NICK=false
    - FPAUTH_FETCH_COOLDOWN=600
    - FPAUTH_MIN_POSTS=25
    - FPAUTH_MONGO_URL=mongodb://mongo:27017/fpauth
